<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use DateTime;

/**
 * Home Controller
 *
 * @property \App\Model\Table\MessagesTable $Messages
 * @property \App\Model\Table\LobbiesTable $Lobbies
 */
class HomeController extends AppController
{
	var $uses = false;

	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->loadModel('Messages');
		$this->loadModel('Lobbies');
	}

	/**
	 * Index method
	 *
	 * @return \Cake\Network\Response|null
	 */
	public function index()
	{
		$title = '';
		$this->set(compact('title'));
		$chat_id = 1; //global chat id

		//get recent messages
		$messages = $this->Messages->find()
			->where(['chat_id' => $chat_id])
			->order(['created_date' => 'ASC'])
			->limit(10)
			->all();

		//todo get playerlist


		//get lobby list
		$lobbies = $this->Lobbies->find()
			->contain(['LobbyStatuses'])
			->all();

		$this->set(compact('messages', 'lobbies'));
		$this->render('index');
	}


}
