<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use DateTime;

/**
 * Home Controller
 *
 * @property \App\Model\Table\MessagesTable $Messages
 * @property \App\Model\Table\LobbiesTable $Lobbies
 */
class HomeController extends AppController
{
	var $uses = false;


	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->loadComponent('Player');
		$this->loadComponent('Chat');
		$this->loadComponent('Lobby');
		$this->loadModel('Messages');
		$this->loadModel('Lobbies');
	}

	/**
	 * Index method
	 *
	 * @return \Cake\Network\Response|null
	 */
	public function index()
	{
		$title = '';
		$this->set(compact('title'));
		$chat_id = 1; //global chat id

		//get current user's username
		$username = $this->Auth->user('username');
		$user_id = $this->Auth->user('id');

		//get recent messages


		$messages = $this->Chat->getMessages($chat_id);

		$players = $this->Player->getPlayerList();

		$lobbies = $this->Lobby->getLobbyList();
		//get lobby list


		$this->set(compact('messages', 'lobbies', 'chat_id', 'username', 'user_id', 'players'));
		$this->render('index');
	}


	public function getPlayerList(){
		$this->autoRender = false;

		if ($this->request->is('post')) {

			$players = $this->Player->getPlayerList();
			$resultJ = json_encode($players);
			$this->response->type('json');
			$this->response->body($resultJ);
			return $this->response;
		}


	}

}
